
spring:
  profiles:
    active: local

server:
  port: 80
  servlet:
    session:
      cookie:
        max-age: 86400 # 86400

---
jasypt:
  encryptor:
    password: mySecretKey

constants:
  keycloak-url: ENC(6UeJ0QC/B9zHz+T/wXKKWgXJ5/FYBK7xF/dWVCpNweN14MZNdJ9fXbDYax1nBwyWg8X1huwRtyE5IhPrn9V7SQ==)
  client-secret: ENC(qSvRXUFAk4C9Xtt/B1jEA0G7+0hvvhg1mdmeTAKTrAAOMrv1kGy3XGTuASCtksADAtj9/EUh3Lo9fEIKZV+hOuZEYOLKTKWYWVXTynEStSg=)
  frontend: ENC(GLprWa0fvoq7R3Vh1T3r07GzybY/aK7apcziAP1gLBvqSp4tzWfQDOUv/HlrAWBiJ9S08T5oCW7kjsBscDZmTA==)
  admin: ENC(kmAns6E2fjAJYZ+VJ55DTR6Ig9qQwUMJqIy6kRIiDRGxDYnC3tHjjE+lhDXpWWE6)
  admin-id: ENC(Mv+/QM86KSgI4sKMd6H0MOMXmJytZXHxYnpQazXNTpuisSCF9MSKbZhRrsljmKAIX02HMqjUQML3u6+3kfKWWUbfW1TgfqFHQnEEsXoO6co=)
  admin-pw: ENC(kmAns6E2fjAJYZ+VJ55DTR6Ig9qQwUMJqIy6kRIiDRGxDYnC3tHjjE+lhDXpWWE6)
  realm: ENC(kbWdaszp7HSheIPFaLRmc0NBJLbEmCrnVWVQmNM7QcX057IeT3I3wDU7ufjNWnCX)

#logging:
#  level:
#    root: debug

# keycloak
spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${constants.keycloak-url}/realms/${constants.realm}
      client:
        provider:
          keycloak:
            issuer-uri: ${constants.keycloak-url}/realms/${constants.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-name: back-office-api
            client-id: back-office-api
            client-secret: ${constants.client-secret}
            scope: openid,offline_access,profile
            authorization-grant-type: authorization_code
#            redirect-uri: ${constants.keycloakUrl}/login/oauth2/code/external
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

---
jasypt:
  encryptor:
    password: ${JASYPT_KEY}

constants:
  keycloak-url: ENC(0dZk38oB1Gm3e7Xl3eb4zTevbp2RREhkLUvkdgRz/heOSh4GtqkJ5rvjcE1umUIkxoquMtiE+GX/cmhZzIL4Ig==)
  client-secret: ENC(mwGuQuXgOPVZ+upjEIGrt9fJMwuc7omECSvUOtaZr1ylbEqN/x+Jp5eh4tx9qQb9YEhQiOz464nJVmh2jJAvkaLdMnq6uwwmX8NfN+IVAxI=)
  frontend: ENC(Z1An8Md7xBH929+x412M2wLdnfQyYQWb7+Wv+cCcsNn5fFQOxw2tQnMLepuVzS5Mw4nC44ijm6rCjslaqb1nPQ==)
  admin: ENC(0mMXBHi59yaWXWRLtiIXGZif4zwsf+futDzetVwJFnX3hxhhZtQZ44QDkI2gku/U)
  admin-id: ENC(3mRJGuDfvxET2n5ICtiA4eLRcLwwXweOzaiykNc0aqOe80Q7BMcSkWpF62HEsL8sIVPjOmbTYz7QEm2+/rVjXK7PGZWydMvBIbw/3otn5Pw=)
  admin-pw: ENC(PLQ+PdMv/lbWmyrFhmyd7ubt7bINwvyVjDGMGV+Xsy16CqnZyl+9/HSAhgbNS2j5)
  realm: ENC(rW4Ij4d66yAHbzdxzQnWAcPib/iNmYJloRByJHiG0Qqm0bNDbjNzp5LrSdzvL7QG)

spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${constants.keycloak-url}/realms/${constants.realm}
      client:
        provider:
          keycloak:
            issuer-uri: ${constants.keycloak-url}/realms/${constants.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-name: back-office-api
            client-id: back-office-api
            client-secret: ${constants.client-secret}
            scope: openid,offline_access,profile
            authorization-grant-type: authorization_code
  datasource:
    url: ENC(m4NvP8vZdtRazN5Uq9QsBODtb09sOlfdXw9v+KbN/y/uLbIb2E6BrTJs1HEDOq6ZcU0Oj4AAIj3RkM1qGczUAxFhnjJLI9X3ofbIdZol6EEQTkD2qLbyz7/3KcEgGxgB0yuN5gLnfCUJqIQN1BIPPg==)
    driverClassName: org.mariadb.jdbc.Driver
    username: ENC(xfQIN2JCVUy9YElSP3OhPV8bkt7aP5u07nWszkIaGlOxeFNaBgIhEuclZua3YghAstbc172vvS3/gW/veb+IPQ==)
    password: ENC(rx4GEztWRP1GFSjFdeJOOftRy7IE5z+vI0qB77mgiz1Qma+CsIb9NdnkB+TtFRO5Naknbk4IlZBC5vObDcDFfg==)
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB103Dialect
