
server:
  port: 80
  servlet:
    session:
      cookie:
        max-age: 86400 # 86400

constants:
#  keycloakUrl: ${KEYCLOAK_URL}
#  clientSecret: ${CLIENT_SECRET}
  keycloakUrl: "http://192.168.0.48:8080"
  clientSecret: "Q0WcVVGIFjQDRH57kQ6oAeWKSvyW3Cci"
#  clientSecret: "9HjW0l2RRUiJk7qx2pgHIacN4Rkm0OMM"

# keycloak
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${constants.keycloakUrl}/realms/sso-test
      client:
        provider:
          keycloak:
            issuer-uri: ${constants.keycloakUrl}/realms/sso-test
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-name: back-office-api
            client-id: back-office-api
            client-secret: ${constants.clientSecret}
            scope: openid,offline_access,profile
            authorization-grant-type: authorization_code
#            redirect-uri: ${constants.keycloakUrl}/login/oauth2/code/external
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
